//Variable
@api = http://localhost:3000/tasks

GET {{api}}

###
GET {{api}}/1
###
GET {{api}}/count



###
POST {{api}}
Content-Type: application/json

{
    "title": "five task",
    "description": "Some description task 5"
}

###
DELETE  {{api}}/1

###
PUT {{api}}/1
Content-Type: application/json

{
    "title": "five task",
    "description": "Some description task 5"
}